version: '3'
services:
  vlibras-dictionary-api:
    build: .
    image: vlibras_dictionary/api:2.1.0
    ports:
      - "3030:3030"
    networks:
      - mongo-net
    environment:
      PORT: 3030
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: "vlibras-db"
      DICTIONARY_REPOSITORY_URL: "http://localhost:8000"
      LOCAL_DICTIONARY_REPOSITORY: /tmp/bundles
      SIGNS_LIST_REFRESH_INTERVAL: 3600000
    depends_on:
      - mongo

  mongo:
    image: mongo
    networks:
      - mongo-net
    volumes:
      - mongo-data:/data/db

networks:
  mongo-net:

volumes:
  mongo-data:
