version: '3'
services:
  vlibras-dictionary-api:
    build: .
    image: vlibras_dictionary/api:2.2.1
    ports:
      - "3030:3030"
    networks:
      - redis-net
      - mongo-net
      - rabbitmq-net
    environment:
      PORT: 3030
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: "vlibras-db"
    depends_on:
      - mongo

  mongo:
    image: mongo
    networks:
      - mongo-net
    volumes:
      - mongo-data:/data/db

networks:
  mongo-net:

volumes:
  mongo-data:
