export default Object.freeze({
  ERROR_CONNECTION_ABORTED: "ECONNABORTED", // Do not rename this value
  ERROR_DICTIONARY_NOT_RESPONSE: "DICTIONARY_NOT_RESPONSE",
  ERROR_DICTIONARY_TIMEOUT_REACHED: "DICTIONARY_TIMEOUT_REACHED",
});
