apiVersion: extensions/v1beta1
#kubectl expose deployment dictionaryapi --port=80 --type=LoadBalancer
#kubectl autoscale deployment dictionaryapi --cpu-percent=70 --min=1 --max=8
kind: Deployment
metadata:
  name: dictionaryapi
  labels:
    app: dictionaryapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dictionaryapi
  template:
    metadata:
      labels:
        app: dictionaryapi
    spec:
      containers:
        - image: vlibras/dictionary-api:08
          name: dictionaryapi
          env:
            - name: DICTIONARY_URL
              value: "sinais.vlibras.lavid.ufpb.br"
            - name: DICTIONARY_PORT
              value: "80"
            - name: PORT
              value: "80"
            - name: DB_HOST
              value: "MONGODB-IP"
            - name: DB_PORT
              value: "MONGODB-PORT"
          ports:
            - containerPort: 80
              name: vl-dic-port
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 20
          volumeMounts:
            - name: dictionary-storage
              mountPath: /exports
      volumes:
        - name: dictionary-storage
          persistentVolumeClaim:
            claimName: dictionary-bundles
      hostNetwork: true
